/*
 * Generated by XDoclet - Do not edit!
 */
package com.clustercontrol.performance.monitor.entity;

/**
 * Primary key for CollectorScopeSnap.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version 4.0.1
 */
public class CollectorScopeSnapPK
extends java.lang.Object
implements java.io.Serializable
{

	private static final long serialVersionUID = 3164953521386366076L;

	public java.lang.String collectorId;
	public java.lang.String facilityId;

	public CollectorScopeSnapPK()
	{
	}

	public CollectorScopeSnapPK( java.lang.String collectorId,java.lang.String facilityId )
	{
		this.collectorId = collectorId;
		this.facilityId = facilityId;
	}

	public java.lang.String getCollectorId()
	{
		return collectorId;
	}
	public java.lang.String getFacilityId()
	{
		return facilityId;
	}

	public void setCollectorId(java.lang.String collectorId)
	{
		this.collectorId = collectorId;
	}
	public void setFacilityId(java.lang.String facilityId)
	{
		this.facilityId = facilityId;
	}

	@Override
	public int hashCode()
	{
		int _hashCode = 0;
		if (this.collectorId != null) _hashCode += this.collectorId.hashCode();
		if (this.facilityId != null) _hashCode += this.facilityId.hashCode();

		return _hashCode;
	}

	@Override
	public boolean equals(Object obj)
	{
		if( !(obj instanceof com.clustercontrol.performance.monitor.entity.CollectorScopeSnapPK) )
			return false;

		com.clustercontrol.performance.monitor.entity.CollectorScopeSnapPK pk = (com.clustercontrol.performance.monitor.entity.CollectorScopeSnapPK)obj;
		boolean eq = true;

		if( this.collectorId != null )
		{
			eq = eq && this.collectorId.equals( pk.getCollectorId() );
		}
		else  // this.collectorId == null
				{
			eq = eq && ( pk.getCollectorId() == null );
				}
		if( this.facilityId != null )
		{
			eq = eq && this.facilityId.equals( pk.getFacilityId() );
		}
		else  // this.facilityId == null
		{
			eq = eq && ( pk.getFacilityId() == null );
		}

		return eq;
	}

	/** @return String representation of this pk in the form of [.field1.field2.field3]. */
	@Override
	public String toString()
	{
		StringBuffer toStringValue = new StringBuffer("[.");
		toStringValue.append(this.collectorId).append('.');
		toStringValue.append(this.facilityId).append('.');
		toStringValue.append(']');
		return toStringValue.toString();
	}

}
